# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push tags begin with 'v'
  push:
    tags:
      - v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # ubuntu-18.04 for glibc version compatibility
        os: [ubuntu-18.04, windows-latest]
        include:
          - os: windows-latest
            script_name: scripts/build.ps1
          - os: ubuntu-18.04
            script_name: scripts/build.sh

          # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - id: certificate
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'certificate.p12'
          encodedString: ${{ secrets.CODE_SIGN_CERT }}

      - id: build
        run: ${{ matrix.script_name }}
        env:
          CODESIGN_CERTIFICATE: ${{ steps.certificate.outputs.filePath }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          DECART_SERVICE_ACCOUNT: ${{ secrets.DECART_SERVICE_ACCOUNT }}

      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.DECART_SERVICE_ACCOUNT }}
          path: ${{ steps.build.outputs.artifact }}
          destination: build.aixmed.com/test

      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag-template: 'v$RESOLVED_VERSION'
        categories:
          - title: 'üöÄ Features'
            labels:
              - 'feature'
              - 'enhancement'
          - title: 'üêõ Bug Fixes'
            labels:
              - 'fix'
              - 'bugfix'
              - 'bug'
          - title: 'üß∞ Maintenance'
            label:
              - 'chore'
              - 'bump'
        template: |
          ## What‚Äôs Changed

          $CHANGES
